name: Unit test (Ubuntu)

on:
  push:
    branches:
      - master
  pull_request:
  merge_group:

jobs:
  test:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: oracle
          java-version: 21

      - name: Run unit tests
        run: sh ./build.sh

      - name: Upload Unit Test Reports
        uses: actions/upload-artifact@v4
        if: ${{ always() }}  # Ensures upload even if tests fail
        with:
          name: unit-test-reports
          path: app/build/reports/tests

      - name: Upload coverage reports to Codecov
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov
