name: E2e Test

on:
  push:
    branches: [ master ]
  pull_request:
  merge_group:

permissions:
  contents: read

jobs:
  test:
    name: Run E2E Tests
    runs-on: self-hosted
    timeout-minutes: 40
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      matrix:
        api-level: [28]
        target: [default]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: oracle
          java-version: 21
          architecture: x64

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install Ganache
        run: npm install -g ganache

      - name: Prepare and run E2E tests
        run: |
          rm -rf ./output
          mkdir ./output
          
          adb shell settings put secure long_press_timeout 1500
          adb shell settings put global window_animation_scale 0.0
          adb shell settings put global transition_animation_scale 0.0
          adb shell settings put global animator_duration_scale 0.0
          adb shell settings put secure show_ime_with_hard_keyboard 0

          ganache --chain.chainId 2 -h 0.0.0.0 -p 8555 \
            -m "horse light surface bamboo combine item lumber tunnel choose acid mail feature" > output/ganache.log 2>&1 &
          GANACHE_PID=$!

          adb logcat > output/emulator.log &
          LOGCAT_PID=$!

          ./gradlew :app:uninstallAll :app:connectedNoAnalyticsDebugAndroidTest -x lint -PdisablePreDex

          kill $GANACHE_PID || true
          kill $LOGCAT_PID || true

      - name: Upload test results
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: e2e-tests-results
          path: output/

  cleanup:
    name: Cleanup Emulator
    if: ${{ always() }}
    needs: test
    runs-on: self-hosted
    steps:
      - name: Uninstall app
        run: ./gradlew :app:uninstallAll
