name: Comments Android lint warnings on pull request

on: pull_request

jobs:
  lint:
    name: Comments lint result on PR
    runs-on: macos-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: oracle
          java-version: 21
          cache: gradle

      - name: Run detekt (Kotlin static analysis)
        run: ./gradlew :app:detekt
        continue-on-error: true   # Do not fail the workflow if detekt fails

      - name: Run Android Lint
        run: ./gradlew :app:lintAnalyticsDebug

      - name: Report lint and detekt results on PR
        env:
          PR_NUMBER: ${{ github.event.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew report --no-configuration-cache -PgithubPullRequestId=$PR_NUMBER -PgithubToken=$GITHUB_TOKEN
