name: Android lint

on:
  push:
    branches:
      - master
  pull_request:
  merge_group:

jobs:
  lint:
    name: Comments lint result on Master
    runs-on: macos-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history, useful for accurate linting

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: oracle
          java-version: 21
          cache: gradle

      - name: Run detekt (Kotlin static analysis)
        run: ./gradlew :app:detekt
        continue-on-error: true  # Allow workflow to continue even if detekt finds issues

      - name: Run Android Lint
        run: ./gradlew :app:lintAnalyticsDebug
